
* Layout

Use bullets instead of Org's standard stars. Found [[http://cestlaz.github.io/posts/using-emacs-2-org/#.Wb1EQY4pCfU][here]].

#+BEGIN_SRC emacs-lisp
(use-package org-bullets
  :ensure t
  :config
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC

I like indentation by default. I find it easier to read.

#+BEGIN_SRC emacs-lisp
(setq org-startup-indented t)
#+END_SRC

* Key Bindings

I found the following key bindings in the condensed Org manual.

#+BEGIN_SRC emacs-lisp
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-cb" 'org-iswitchb)
#+END_SRC

* =org-capture=

Specify the primary capture file (I only use one).

#+BEGIN_SRC emacs-lisp
(setq org-default-notes-file (concat org-directory "/capture.org"))
#+END_SRC

** Capture Templates

Define capture templates here. I found [[https://orgmode.org/manual/Capture-templates.html][the manual]] to be pretty helpful.

#+BEGIN_SRC emacs-lisp
(setq org-capture-templates
      (quote (("t" "todo" entry (file (concat org-directory "/capture.org"))
               "* TODO %?\n%U\n%a\n")
              ("n" "note" entry (file (concat org-directory "/capture.org"))
               "* %? :NOTE:\n%U\n%a\n")
              ("j" "Journal" entry (file+datetree (concat org-directory "/capture.org"))
               "* %?\n%U\n")
              )))
#+END_SRC

* =org-agenda=

I found a great =org-mode= configuration file [[https://github.com/kapilreddy/dotemacs/blob/master/configurations/org-mode-config.el][here]]; it defines a
custom variable (=org-base-directory=) that we can change to whatever
we want. We then use =org-agenda-files= to select a =list= of directories
that contain our main =org= files.

#+BEGIN_SRC emacs-lisp
(setq org-base-directory "~/org/")

(setq org-agenda-files (list (concat org-base-directory "work")
			     (concat org-base-directory "personal")))
#+END_SRC

* =org-refile=

For =org-refile=, we want our refile targets to be our main =org= files.
We also enable some nice quality of life settings. Read more [[https://blog.aaronbieber.com/2017/03/19/organizing-notes-with-refile.html][here]].

#+BEGIN_SRC emacs-lisp
(setq org-refile-targets
      '((nil :maxlevel . 1)
	(org-agenda-files :maxlevel . 1)))

(setq org-outline-path-complete-in-steps nil)

(setq org-refile-use-outline-path 'full-file-path)
#+END_SRC

* Source Blocks

#+BEGIN_SRC emacs-lisp
(setq org-src-fontify-natively t)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defface org-block-begin-line
    '((t (:underline "#6CA0A3" :foreground "#DCDCCC" :background "#5F5F5F")))
    "Face used for the line delimiting the begin of source blocks.")

;; Doesn't work, see note.
(defface org-block-background
    '((t (:background "#4F4F4F")))
    "Face used for the source block background.")

(defface org-block-end-line
    '((t (:overline "#6CA0A3" :foreground "#DCDCCC" :background "#5F5F5F")))
    "Face used for the line delimiting the end of source blocks.")
#+END_SRC

NOTE: =org-block-background= no longer works; see [[https://emacs.stackexchange.com/questions/14824/org-block-background-font-not-having-effect][here]] for more info.

* Task States

Documentation [[https://orgmode.org/manual/Workflow-states.html][here]].

#+BEGIN_SRC emacs-lisp
(setq org-todo-keywords
  '((sequence "TODO" "|" "DONE" "CANCELLED")))
#+END_SRC
