
* Package Management

** Initialization stuff

You can find an explanation for the following [[https://emacs.stackexchange.com/questions/22717/what-does-require-package-mean-for-emacs-and-how-does-it-differ-from-load-fil][here]].

#+BEGIN_SRC emacs-lisp
(require 'package)
#+END_SRC

Explanation [[https://www.reddit.com/r/emacs/comments/1rdstn/set_packageenableatstartup_to_nil_for_slightly/][here]].

#+BEGIN_SRC emacs-lisp
(package-initialize)
(setq package-enable-at-startup nil)
#+END_SRC

** =use-package= Bootsrap

We use =use-package= for package management and configuration. It's like 
Puppet for Emacs! See =package.el= for more information.

#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
#+END_SRC

** Repository Management

NOTE: For Windows, you'll need GnuTLS DLLs. (Emacs for Windows isn't built with TLS support.)
Instructions found [[http://חנוך.se/diary/how_to_enable_GnuTLS_for_Emacs_24_on_Windows/index.en.html][here]].

This enables the MELPA repository on start up.

#+BEGIN_SRC emacs-lisp
(add-to-list 'package-archives
     '("melpa" . "https://melpa.org/packages/") t)
#+END_SRC

* Init File Include Statements

If you need descriptions for any of these, just check each file for more info.

#+BEGIN_SRC emacs-lisp
(org-babel-load-file
 (expand-file-name "packages.org"
                   user-emacs-directory))

(org-babel-load-file
 (expand-file-name "mail.org"
                   user-emacs-directory))

(org-babel-load-file 
 (expand-file-name "org.org"
                   user-emacs-directory))
#+END_SRC

* Modifications to Core Emacs Functionality

Here we'll change the default behaviors of Emacs.

** Buffer Management

=ibuffer= allows for buffer management from a nice menu.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x C-b") 'ibuffer)
(autoload 'ibuffer "ibuffer" "List buffers." t)
#+END_SRC

** Text Editing

I like line numbers, so I enable them globally.

#+BEGIN_SRC emacs-lisp
(global-linum-mode 1)
#+END_SRC

Some color themes increase line number font sizes with =org-mode= headers
and the fixed width of the line number column cuts it off. I found a post
[[https://unix.stackexchange.com/questions/29786/font-size-issues-with-emacs-in-linum-mode/30087#30087][here]] that suggests a fix.

#+BEGIN_SRC emacs-lisp
(set-face-attribute 'linum nil :height 100)
#+END_SRC

** Startup

Who likes the startup message?

#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)
#+END_SRC
